# Generated by Django 4.2.7 on 2024-01-06 03:42

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nama_lengkap', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('gender', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('jabatan', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=20)),
                ('status_barang', models.CharField(max_length=20)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('jenis_barang', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('nama_barang', models.CharField(blank=True, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('id_barang', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('jumlah_barang', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_peminjaman', models.DateField()),
                ('tanggal_pengembalian', models.DateField()),
                ('status_peminjaman', models.CharField(max_length=20, null=True)),
                ('durasi_peminjaman', models.IntegerField(blank=True, null=True)),
                ('id_akun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_barang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.barang')),
            ],
        ),
    ]
