# Generated by Django 4.2.7 on 2023-11-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('gender', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('jabatan', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('no_hp', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=20)),
                ('status_barang', models.CharField(max_length=20)),
                ('jenis_barang', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_peminjaman', models.DateField()),
                ('tanggal_pengembalian', models.DateField()),
                ('status_peminjaman', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_barang', models.IntegerField()),
            ],
        ),
    ]
