# Generated by Django 4.2.7 on 2023-12-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.AddField(
            model_name='barang',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='durasi_peminjaman',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peminjaman',
            name='id_akun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.akun'),
        ),
        migrations.AddField(
            model_name='stock',
            name='id_barang',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='nama_barang',
            field=models.CharField(blank=True, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='jumlah_barang',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
