# Generated by Django 4.2.7 on 2024-01-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='nama_barang',
            field=models.CharField(max_length=100),
        ),
    ]
