# Generated by Django 4.2.7 on 2023-12-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_stock_id_barang_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='serial_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
