# Generated by Django 4.2.7 on 2023-12-14 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_barang_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjaman',
            name='id_barang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.barang'),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='status_peminjaman',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
