# Generated by Django 4.2.7 on 2024-01-15 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_barang_id_akun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='id_akun',
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='id_akun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='id_barang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman_set', to='api.barang'),
        ),
    ]
