# Generated by Django 4.2.7 on 2024-01-15 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_barang_id_akun_alter_peminjaman_id_akun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='id_barang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.barang'),
        ),
    ]
