# Generated by Django 4.2.7 on 2023-12-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_peminjaman_id_barang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
