# Generated by Django 4.2.7 on 2024-01-15 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_barang_nama_peminjam_alter_peminjaman_id_akun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='nama_peminjam',
        ),
        migrations.AddField(
            model_name='barang',
            name='nama_peminjam',
            field=models.ManyToManyField(through='api.Peminjaman', to=settings.AUTH_USER_MODEL),
        ),
    ]
