# Generated by Django 4.2.7 on 2024-01-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_barang_nama_peminjam_barang_nama_peminjam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='nama_peminjam',
        ),
    ]
